### PR TITLE
Screw holes through lid

### PR DESCRIPTION
**Pull request by GreenEllipsis**
Added yappThroughLid parameter to connectors array which generates the screw hole through the lid instead of through the base.

### CODE REVIEW

**Comment by mrWheel** [comment]
@GreenEllipsis ,

Can you please elaborate how this extra parameter works? What does it do with the insert position?

Do you have some pictures using this parameter?

**Comment by mrWheel** [comment]
@GreenEllipsis ,

At this moment there is heavy development going on by @rosenhauer.
Before I will merge your request I want to wait till @rosenhauer is done!

**Comment by GreenEllipsis** [comment]
> @GreenEllipsis ,
> 
> Can you please elaborate how this extra parameter works? What does it do with the insert position?
> 
> Do you have some pictures using this parameter?

Yeah, it does nothing with the insert. Gotta fix that.

**Comment by mrWheel** [comment]
@GreenEllipsis, Brian,

This function is part of v3.0

**Comment by ettom** [comment]
@mrWheel, did this ever make it to v3.0?

**Comment by mrWheel** [comment]
@GreenEllipsis ,

The name "yappThroughLid" is part of v3 but I'm not sure it is with the same functionality as you intended it to be.

Ask @rosenhauer

**Comment by ettom** [comment]
The PCB(s) would still be mounted on the base which would make it pretty awkward to access them when mounted on a wall.

**Pull request closed without merging**
