### PR TITLE
Cutouts fix and yappPCBCoord renames

### PR DESCRIPTION
**Pull request by rosenhauer**
For Bug#1 and #3
The position on the Left,Right,Front,Back faces has been fixed for the PCB Coordinate system

On the cutouts the X position was from the edge closest to the global origin but I found it easier to deal with with the left of the face being the zero point.   

//-- padding between pcb and inside wall
paddingFront        = 41;
paddingBack         = 31;
paddingRight        = 21;
paddingLeft         = 1;

Closest to global origin (how it was in v19) with all of the rectangles having X value of 0:
image

Left of face (new option) again with X having value of 0:
image

I have coded for both with yappLeftOrigin optional cutouts  parameter on the Top, Right and Back faces. It does nothing on the other faces.

### CODE REVIEW

**Comment by mrWheel** [comment]
@rosenhauer,

Found some strange behaviour and/or bugs ..

**-1-**
Compiling the Template I got this message:
```
CGAL cache size in bytes: 100775344
Compiling design (CSG Products normalization)...
WARNING: Normalized tree is growing past 200000 elements. Aborting normalization.  
WARNING: CSG normalization resulted in an empty tree 
Compiling background (3 CSG Trees)...
```
And than nothing happens.
Change the comment in `YAPPgenerator_v21.scad` and the `YAPP_Template_v21.scad` from 100000 to 200000:

**-2-**
```
Remove all references to `cutoutGrills` as you made a far nicer solution.

// This design is parameterized based on the size of a PCB.
//
//  for many or complex cutoutGrills you might need to adjust
//  the number of elements:
//
//      Preferences->Advanced->Turn of rendering at 200000 elements
//                                                  ^^^^^^

```
**-3-**
At least one of the hookLid modules should go through the wall's and lidPlane or basePlane (but preferable both then we can go half way of the wall's and planes).
F.i. many round chassis mount parts have flat sides so they won't rotate (Both cubes done on the Inside and Outside):

Screenshot 2023-11-26 at 12 08 59


With the new v2.1 this is what happens (I made the blue cubes thicker than needed to show the effect):

Screenshot 2023-11-26 at 12 04 06


The hook modules now stay exactly inside or outside the box.. so there is no way to make a hole for such parts.

**-4-**
The `pushButtons[]` when `yappCircle` shows a strange artefact:

Screenshot 2023-11-26 at 12 34 48

**-5-**
I still get a lot of warnings that are probably due to the fact that I don't use (or define) all of the array's possible. This happens f.i. if you modify an older box that does not have, or need, all the possibilities of v2.1
```
[WARNING: undefined operation (undefined + number) in file ../YAPP_Box/library/YAPPgenerator_v21.scad, line 1642](https://github.com/mrWheel/YAPP_Box/pull/1642,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (undefined + number) in file ../YAPP_Box/library/YAPPgenerator_v21.scad, line 1643](https://github.com/mrWheel/YAPP_Box/pull/1643,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (-undefined) in file ../YAPP_Box/library/YAPPgenerator_v21.scad, line 1528](https://github.com/mrWheel/YAPP_Box/pull/1528,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: Unable to convert translate([undef, undef, 0]) parameter to a vec3 or vec2 of numbers in file ../../../openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad, line 1556](https://github.com/mrWheel/YAPP_Box/pull/1556,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (number - undefined) in file ../YAPP_Box/library/YAPPgenerator_v21.scad, line 1560](https://github.com/mrWheel/YAPP_Box/pull/1560,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (undefined - number) in file ../YAPP_Box/library/YAPPgenerator_v21.scad, line 1560](https://github.com/mrWheel/YAPP_Box/pull/1560,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: Unable to convert translate([0, 0, undef]) parameter to a vec3 or vec2 of numbers in file ../../../openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad, line 1560](https://github.com/mrWheel/YAPP_Box/pull/1560,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (undefined + number) in file ../YAPP_Box/library/YAPPgenerator_v21.scad, line 1562](https://github.com/mrWheel/YAPP_Box/pull/1562,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: Problem converting rotate(a=[0, 0, undef]) parameter in file ../../../openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad, line 3499](https://github.com/mrWheel/YAPP_Box/pull/3499,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (undefined + number) in file ../YAPP_Box/library/YAPPgenerator_v21.scad, line 1642](https://github.com/mrWheel/YAPP_Box/pull/1642,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (undefined + number) in file ../YAPP_Box/library/YAPPgenerator_v21.scad, line 1643](https://github.com/mrWheel/YAPP_Box/pull/1643,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (-undefined) in file ../YAPP_Box/library/YAPPgenerator_v21.scad, line 1528](https://github.com/mrWheel/YAPP_Box/pull/1528,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: Unable to convert translate([undef, undef, 0]) parameter to a vec3 or vec2 of numbers in file ../../../openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad, line 1556](https://github.com/mrWheel/YAPP_Box/pull/1556,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (number - undefined) in file ../YAPP_Box/library/YAPPgenerator_v21.scad, line 1560](https://github.com/mrWheel/YAPP_Box/pull/1560,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (undefined - number) in file ../YAPP_Box/library/YAPPgenerator_v21.scad, line 1560](https://github.com/mrWheel/YAPP_Box/pull/1560,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: Unable to convert translate([0, 0, undef]) parameter to a vec3 or vec2 of numbers in file ../../../openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad, line 1560](https://github.com/mrWheel/YAPP_Box/pull/1560,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (undefined + number) in file ../YAPP_Box/library/YAPPgenerator_v21.scad, line 1562](https://github.com/mrWheel/YAPP_Box/pull/1562,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: Problem converting rotate(a=[0, 0, undef]) parameter in file ../../../openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad, line 3499](https://github.com/mrWheel/YAPP_Box/pull/3499,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
Compiling design (CSG Products generation)... 
```

**Comment by mrWheel** [comment]
**-3-**
The way you have now implemented it is perfect. I don’t understand how an extra `yappFill ` param in the cutouts would work.
It should be something as a param in the hook modules..

**-4-**
A rounded transition would work but if you make it like the rectangle switches that would satisfy my needs.

**-5-**
Well, I don’t alway’s start from the template. For simple boxes I only define the needed array’s. But sanity checking would probably help users also.

**Comment by mrWheel** [comment]
@rosenhauer,

did you see point 6?

**-6-**
What happened to the yappConnWithPCB parameter in connectors?
Is it still possible to make connectors that do not have a PCB wedged in?

**Comment by rosenhauer** [comment]
#6 I had added the comment : //yappConnWithPCB - Depreciated use yappCoordPCB 
 but looking at it again I think I may have misunderstood what it was doing.  I thought it just made the position use the PCB.  I think I need to add it back in and have it adjust the height of the lid part to be PCB thickness shorter to allow room for the PCB.  

I'm still a little confused on the hooks.  I implemented them to have the object trimmed to either the inside or outside of the shell. 
 For example on the Inside hooks remove everything from the midpoint of the shell outward.  and the Outside removes everything from the midpoint inward.  This allows objects like hinges and latches to be added and connected to the shell without extending through the shell.  It looks like your intention was to have it used for example to add flat sides to a round cutout.  I see several options:

1. I could add a hookShell that would trim it to only be within the shell.  
2. I can change the outside to use the inside of the shell instead of the midpoint (and inside use the outside). This would allow you to add a rectangle (or any other shape) the thinckness of the shell to accomplish the flats.
3. Add a new shape yappCircleWithFlats and have the Width param define the width between the flats positioned at 0 and 180 degrees of the circle.  I could also add a yappCircleWithKey and use the width/length to define a single key at the edge at 0 degrees (you could use the rotate param to move it if needed).   I think that would cover most types of mounting holes. 

image

R=10, W=4 L=4
image

I'm leaning towards doing #2 and #3.  Let me know your thoughts.

**Comment by mrWheel** [comment]
> #6 I had added the comment : //yappConnWithPCB - Depreciated use yappCoordPCB but looking at it again I think I may have misunderstood what it was doing. I thought it just made the position use the PCB. I think I need to add it back in and have it adjust the height of the lid part to be PCB thickness shorter to allow room for the PCB.

Or … if the connector is inside the PCB then leave room for the PCB thickness and if outside the PCB do not.
But that programs intelligences into the code.
I prefere to add `yappConnWithPCB` back. 

> 
> I'm still a little confused on the hooks. I implemented them to have the object trimmed to either the inside or outside of the shell. For example on the Inside hooks remove everything from the midpoint of the shell outward. and the Outside removes everything from the midpoint inward. This allows objects like hinges and latches to be added and connected to the shell without extending through the shell. It looks like your intention was to have it used for example to add flat sides to a round cutout. I see several options:
> 
> 1. I could add a hookShell that would trim it to only be within the shell.

Better not.

> 2. I can change the outside to use the inside of the shell instead of the midpoint (and inside use the outside). This would allow you to add a rectangle (or any other shape) the thinckness of the shell to accomplish the flats.

You implemented it correct. But instead of trimming to the outside or inside of the shell you should trim from inside or outside to *half the wall or plane*.
Using the center of the wall or plane is the way to go.

> 3. Add a new shape yappCircleWithFlats and have the Width param define the width between the flats positioned at 0 and 180 degrees of the circle.  I could also add a yappCircleWithKey and use the width/length to define a single key at the edge at 0 degrees (you could use the rotate param to move it if needed).   I think that would cover most types of mounting holes.

**3** Better not as it limits the shape to a specific situation.

> I'm leaning towards doing #2 and #3. Let me know your thoughts.

**Comment by rosenhauer** [comment]
> You implemented it correct. But instead of trimming to the outside or inside of the shell you should trim from inside or outside to half the wall or plane.
> Using the center of the wall or plane is the way to go.

It is currently going from the midpoint but the cutouts are being applied after the hooks so the cutout is also cutting the hook.  The hooks are added while the shell is created.  If you want it done later I'll have to move some code around but you then wouldn't be able to cut shapes out of the hooks.  I could change the current ones to "pre" versions and add "post" versions so you could decide when you wanted them added.  

3 Adding the new shapes was trivial as neither needed new parameters so I already added those.

**Comment by mrWheel** [comment]
> It is currently going from the midpoint but the cutouts are being applied after the hooks so the cutout is also cutting the hook. 

Ok, I thought I read that but was not sure my English understood it correct.

> The hooks are added while the shell is created. If you want it done later I'll have to move some code around but you then wouldn't be able to cut shapes out of the hooks. I could change the current ones to "pre" versions and add "post" versions so you could decide when you wanted them added.

I think I don’t quite understand what you write. 
We need extra modules?
Is it difficult to implement? Maybe do that and see how it workout.

> 3 Adding the new shapes was trivial as neither needed new parameters so I already added those.

Ok. But before I can update the docs I need a `README.md` with API changing info for v2.1 and some examples of how to use these changes.

**Comment by rosenhauer** [comment]
> did you see point 6?
> 
> **-6-** What happened to the yappConnWithPCB parameter in connectors? Is it still possible to make connectors that do not have a PCB wedged in?

Looking at the code if you use the PCB coordinates it does leave a gap for the PCB.  If you use Box coordinates the connectors will touch (no gap).

**Pull request merged**
