### PR TITLE
add fillets and other fixes

### PR DESCRIPTION
**Pull request by rosenhauer**
1. Add fillets to LightTubes, pcbStandoff, Connectors,
2. Add colorLid and colorBase back in (not sure when they got removed)
3. Moved lidHookOutside, buildLightTubes, buildButtons, lidHookInside inside lidShell() so they can be cut by the inspection planes.
4. Fixed Snap placement min/max calculations
5. Fixed a LED to LID typo.

### CODE REVIEW

**Comment by mrWheel** [comment]
@rosenhauer: Great work

**Comment by mrWheel** [comment]
@rosenhauer 
Dave,
doing some testing and I find some peculiarities..

`1)`
With (f.i.) "connectors()" there are 10 parameters to fill:
```
// (0) = posx
// (1) = posy
// (2) = pcbStandHeight
// (3) = screwDiameter
// (4) = screwHeadDiameter
// (5) = insertDiameter
// (6) = outsideDiameter
// (7) = flangeHeight
// (8) = flangeDiam
// (9) = { yappConnWithPCB }
// (10) = { yappAllCorners | yappFrontLeft | yappFrontRight | yappBackLeft | yappBackRight }
```
It looks like 7 and 8 are not used if `useFillet` is `true`. Maybe (my choice) in stead of `filletRadius` you can use parameter 8 and remove `filletRadius`.

`2)`
Given this array:
```
connectors   =  [
                  [ 8, 8, 4, screwDiam, 6, insertDiam, 7, 5, 15, yappFrontLeft]
                , [ 5, 25, 4, screwDiam, 6, insertDiam, 7, 5, 15, yappConnWithPCB, yappFrontRight]
                ]
```
The output is:
Screenshot 2023-11-11 at 12 12 34
As you can see the room for the insert is gone on the left connector. Not sure wether this was a bug already in the code or a new one..

`3)`
Preferred Coding Style is:
 ```
       if (useFillet) 
       {
          translate([0,0,(pcbTop2Lid/2)-lidPlaneThickness])
          color("red") pinFillet(-(tWidth+(tWall*2))/2,filletRadius);
        } // ifFillet
```
and:
 ```
module pinFillet (pinRadius, filletRadius=0, facets=36) 
{
  // Handle defaults
  fr = (filletRadius == 0) ? (pinRadius < 0) ? -pinRadius : pinRadius : filletRadius; 
  voffset = (pinRadius < 0) ? 0 : fr;
  voffset2 = (pinRadius < 0) ? -fr : 0;  
  pr = (pinRadius < 0) ? -pinRadius : pinRadius;
  step=360/ facets;
  translate([0,0, voffset2])
  difference() 
  {
    difference() 
    {
      cylinder(h=fr, r=pr+fr, center=false);
      for(dr=[0:step:360]) 
        rotate([0,0,dr]) 
        translate([pr+fr,0, voffset]) 
        rotate([90,0,0]) cylinder(h=fr*3, 
        r=fr, center=true,$fn=20);
    }
    translate([0,0, -1]) 
    cylinder(h=fr+2, r=pr-.04, center=false);
  }
}  //  pinFillet()
```
Would you please be so kind to look into this?

**Comment by rosenhauer** [comment]
I was trying to not break the parameters. But I agree that changing flangeHeight to addFillet (Boolean) and flangeDiam to filletRadius - with 0 being use default.  

I'll look at #2 also.

**Comment by mrWheel** [comment]
I don’t want to mimmick Windows with backwards compatibility all-the-way!

Also adapt `YAPPtemplate.scad` to the new parameters and maybe also some of the examples.

Mind you that the `flangeHeigth` and `flangeDiam` are numbers in case `useFillets = false`!

Thanks for the great `fillets`.

**Comment by rosenhauer** [comment]
What's your thought of the following.

1. Remove filletRadius global
2. Remove the useFillet global
3. Add a yappAddFillet constant that can be added to the end of any item that you want the fillets on instead of the global useFillet (pcbStands, connectors, baseMounts (didn't have this one before), lightTubes, pushButtons) 
4. have the system auto calculate the proper fillet size (should be 1/2 of the thinner of the wall thickness that it is joining (according to "Designing for plastics").  I was using the wall thickness before but it was overkill on most of them.

**Comment by mrWheel** [comment]
1. YES!
2. Ok, I can live with that if you implement 3
3. Great! Most ‘baseMounts’ are rather thick so I don’t know wether this has priority (I can live the way they are now but if you have the time: be my guest).
4. I like to have control over the diameter of the flanges for special cases but maybe a value of zero can make it auto calculate?

**Pull request merged**
