### PR TITLE
fix and enhance mount; fix mask

### PR DESCRIPTION
**Pull request by GreenEllipsis**
Bugfixes
* fixed positioning error of mount when pos less than 2x screwDiameter
* fixed cutout mask positioning error  on inverted Z faces, which prevented them from working

Backwards-compatible enhancements
* removed unnecessary and counterintuitive positioning restrictions on mounts
* added ability to set distance between mounting hole and shell wall
* added alpha channel debug setting to lid color
* added import of PCB mesh file in debug settings

### CODE REVIEW

**Review by rosenhauer — CHANGES_REQUESTED** [review]
Looks good overall.

Could you change lidAlpha to alphaLid and add alphaBase also.

**Comment by mrWheel** [comment]
@GreenEllipsis ,

At this moment there is heavy development going on by @rosenhauer.
Before I will merge your request I want to wait till @rosenhauer is done!

**Comment by GreenEllipsis** [comment]
> Looks good overall.
> 
> Could you change lidAlpha to alphaLid and add alphaBase also.

Done

**Comment by mrWheel** [comment]
@GreenEllipsis, Brian,

This is already fixed in v3.0

Thanks!

**Pull request closed without merging**
