### PR TITLE
Fixed logic error.

### PR DESCRIPTION
**Pull request by rosenhauer**

### CODE REVIEW

**Comment by mrWheel** [comment]
@rosenhauer , hi Dave,

Pulled the latest from github.

If I just run the YAPP_Template_v21.scad I get a lot of warnings that I can not all understand.
```
Parsing design (AST generation)...
Compiling design (CSG Tree generation)...
[WARNING: Ignoring unknown variable 'Shape_Hexagon' in file YAPP_Template_v21.scad, line 299](https://github.com/mrWheel/YAPP_Box/pull/299,/Users/x/Documents/openSCAD/YAPP_Box/YAPP_Template_v21.scad) 
[WARNING: Ignoring unknown variable 'honeycombMask' in file YAPP_Template_v21.scad, line 299](https://github.com/mrWheel/YAPP_Box/pull/299,/Users/x/Documents/openSCAD/YAPP_Box/YAPP_Template_v21.scad) 
[WARNING: Ignoring unknown variable 'Shape_Hexagon' in file YAPP_Template_v21.scad, line 330](https://github.com/mrWheel/YAPP_Box/pull/330,/Users/x/Documents/openSCAD/YAPP_Box/YAPP_Template_v21.scad) 
[WARNING: Ignoring unknown variable 'barsMask' in file YAPP_Template_v21.scad, line 330](https://github.com/mrWheel/YAPP_Box/pull/330,/Users/x/Documents/openSCAD/YAPP_Box/YAPP_Template_v21.scad) 
ECHO: "YAPP=========================================="
ECHO: "YAPP:", pcbLength = 150
ECHO: "YAPP:", pcbWidth = 100
ECHO: "YAPP:", pcbThickness = 1.6
ECHO: "YAPP:", paddingFront = 41
ECHO: "YAPP:", paddingBack = 1
ECHO: "YAPP:", paddingRight = 1
ECHO: "YAPP:", paddingLeft = 1
ECHO: "YAPP=========================================="
ECHO: "YAPP:", standoffHeight = 10
ECHO: "YAPP:", standoffPinDiameter = 2.4
ECHO: "YAPP:", standoffDiameter = 7
ECHO: "YAPP=========================================="
ECHO: "YAPP:", buttonWall = 2
ECHO: "YAPP:", buttonPlateThickness = 2.5
ECHO: "YAPP:", buttonSlack = 0.25
ECHO: "YAPP:", buttonCupDepth = 3
ECHO: "YAPP=========================================="
ECHO: "YAPP:", baseWallHeight = 25
ECHO: "YAPP:", lidWallHeight = 23
ECHO: "YAPP:", wallThickness = 2
ECHO: "YAPP:", ridgeHeight = 3
ECHO: "YAPP:", roundRadius = 2
ECHO: "YAPP:", shellLength = 196
ECHO: "YAPP:", shellInsideLength = 192
ECHO: "YAPP:", shellWidth = 106
ECHO: "YAPP:", shellInsideWidth = 102
ECHO: "YAPP:", shellHeight = 50.5
ECHO: "YAPP:", shellpcbTop2Lid = 48
ECHO: "YAPP=========================================="
ECHO: "YAPP:", pcbX = 3
ECHO: "YAPP:", pcbY = 3
ECHO: "YAPP:", pcbZ = 12.85
ECHO: "YAPP:", pcbZlid = 37.65
ECHO: "YAPP=========================================="
ECHO: "YAPP:", shiftLid = 5
ECHO: "YAPP:", onLidGap = 10
ECHO: "YAPP=========================================="
ECHO: "YAPP:", Version = "v2.1.0 (20-11-2023)"
ECHO: "YAPP:   copyright by Willem Aandewiel"
ECHO: "YAPP=========================================="
[WARNING: Problem converting rotate(a=[0, 0, undef]) parameter in file library/YAPPgenerator_v21.scad, line 3459](https://github.com/mrWheel/YAPP_Box/pull/3459,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (-undefined) in file library/YAPPgenerator_v21.scad, line 3460](https://github.com/mrWheel/YAPP_Box/pull/3460,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (undefined / number) in file library/YAPPgenerator_v21.scad, line 3460](https://github.com/mrWheel/YAPP_Box/pull/3460,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (-undefined) in file library/YAPPgenerator_v21.scad, line 3460](https://github.com/mrWheel/YAPP_Box/pull/3460,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (undefined / number) in file library/YAPPgenerator_v21.scad, line 3460](https://github.com/mrWheel/YAPP_Box/pull/3460,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: Unable to convert translate([undef, undef, 0]) parameter to a vec3 or vec2 of numbers in file library/YAPPgenerator_v21.scad, line 3460](https://github.com/mrWheel/YAPP_Box/pull/3460,/Users/WillemA/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: Problem converting rotate(a=[0, 0, undef]) parameter in file library/YAPPgenerator_v21.scad, line 3459](https://github.com/mrWheel/YAPP_Box/pull/3459,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (-undefined) in file library/YAPPgenerator_v21.scad, line 3460](https://github.com/mrWheel/YAPP_Box/pull/3460,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (undefined / number) in file library/YAPPgenerator_v21.scad, line 3460](https://github.com/mrWheel/YAPP_Box/pull/3460,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (-undefined) in file library/YAPPgenerator_v21.scad, line 3460](https://github.com/mrWheel/YAPP_Box/pull/3460,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (undefined / number) in file library/YAPPgenerator_v21.scad, line 3460](https://github.com/mrWheel/YAPP_Box/pull/3460,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: Unable to convert translate([undef, undef, 0]) parameter to a vec3 or vec2 of numbers in file library/YAPPgenerator_v21.scad, line 3460](https://github.com/mrWheel/YAPP_Box/pull/3460,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
ECHO: "Print lid"
ECHO: "Side by side"
[WARNING: Problem converting rotate(a=[0, 0, undef]) parameter in file library/YAPPgenerator_v21.scad, line 3459](https://github.com/mrWheel/YAPP_Box/pull/3459,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (-undefined) in file library/YAPPgenerator_v21.scad, line 3460](https://github.com/mrWheel/YAPP_Box/pull/3460,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (undefined / number) in file library/YAPPgenerator_v21.scad, line 3460](https://github.com/mrWheel/YAPP_Box/pull/3460,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (-undefined) in file library/YAPPgenerator_v21.scad, line 3460](https://github.com/mrWheel/YAPP_Box/pull/3460,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: undefined operation (undefined / number) in file library/YAPPgenerator_v21.scad, line 3460](https://github.com/mrWheel/YAPP_Box/pull/3460,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
[WARNING: Unable to convert translate([undef, undef, 0]) parameter to a vec3 or vec2 of numbers in file library/YAPPgenerator_v21.scad, line 3460](https://github.com/mrWheel/YAPP_Box/pull/3460,/Users/x/Documents/openSCAD/YAPP_Box/library/YAPPgenerator_v21.scad) 
Compiling design (CSG Products generation)...
Geometries in cache: 141
Geometry cache size in bytes: 757024
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Compiling design (CSG Products normalization)...
Compiling background (3 CSG Trees)...
Normalized tree has 171 elements!
Compile and preview finished.
Total rendering time: 0:00:01.315
```

Do you know about these warnings?

**Comment by mrWheel** [comment]
Did you see [this]([url](https://github.com/mrWheel/YAPP_Box/pull/28)) merge reguest?

is it applicable to the latest version?

**Comment by mrWheel** [comment]
@rosenhauer ,

Did a quick test with the cutouts.
Given this code:
```
//-- pcb dimensions -- very important!!!
pcbLength           = 150; // Front to back
pcbWidth            = 140; // Side to side
pcbThickness        = 1.6;
                            
//-- padding between pcb and inside wall
paddingFront        = 41;
paddingBack         = 21;
paddingRight        = 1;
paddingLeft         = 1;

cutoutsFront = [
                  [10, 0, 10, 15, 0, 0, 0, yappRectangle, yappPCBCoord]
                , [30, 0, 10, 15, 5, 0, 0, yappCircle, yappPCBCoord]
                , [70, 0, 10, 15, 0, 0, 0, yappRectangle, yappBoxCoord]
                , [90, 0, 10, 15, 5, 0, 0, yappCircle, yappBoxCoord]
               ];  


cutoutsBack = [
                  [10, 0, 10, 15, 0, 0, 0, yappRectangle, yappPCBCoord]
                , [30, 0, 10, 15, 5, 0, 0, yappCircle, yappPCBCoord]
                , [70, 0, 10, 15, 0, 0, 0, yappRectangle, yappBoxCoord]
                , [90, 0, 10, 15, 5, 0, 0, yappCircle, yappBoxCoord]
              ];

cutoutsLeft = [
                  [10, 0, 10, 15, 0, 0, 0, yappRectangle, yappPCBCoord]
                , [30, 0, 10, 15, 5, 0, 0, yappCircle, yappPCBCoord]
                , [90, 0, 10, 15, 0, 0, 0, yappRectangle, yappBoxCoord]
                , [110, 0, 10, 15, 5, 0, 0, yappCircle, yappBoxCoord]
              ];

cutoutsRight = [
                  [10, 0, 10, 15, 0, 0, 0, yappRectangle, yappPCBCoord]
                , [30, 0, 10, 15, 5, 0, 0, yappCircle, yappPCBCoord]
                , [70, 0, 10, 15, 0, 0, 0, yappRectangle, yappBoxCoord]
                , [90, 0, 10, 15, 5, 0, 0, yappCircle, yappBoxCoord]
               ];

```
.. the cutouts with yappPCBCoord should be referenced by the top of the PCB. Changing the height of the standoffs should also higher the cutouts. Which it does not!

**Comment by rosenhauer** [comment]
Finally done with family. Will look into all of this tonight.

**Comment by rosenhauer** [comment]
On #2 module minkowskiBox contains the calls.

**Pull request merged**
