### PR TITLE
[WIP; don't merge] support for multiple PCBs

### PR DESCRIPTION
**Pull request by AustinHaigh**
[Work-In-Progress; do not merge] This adds basic support for multiple PCBs in the same box. It is functional enough that I have been using it for my own projects, but it is not done: it doesn't support cutouts yet, and the PCBs are always placed in a row (I'm considering adding support for a grid layout).

Are you interested in adding support for multiple PCBs? I'm happy to keep working on this if you are interested.

Here is a usage example:

// ESP32 board dimensions
esp_dim = [28, 52, 1.5];
esp_holes = [[2.5,           2.5,           3,7],
             [2.5,           esp_dim.x-2.5, 3,7],
             [esp_dim.y-2.5, 2.5,           3,7],
             [esp_dim.y-2.5, esp_dim.x-2.5, 3,7]];

// garage door opener pcb dimensions
gd_dim = [37, 58, 1.5];
gd_holes = [[2.5,          2.5,           3,7],
            [2.5,          gd_dim.x-2.5,  3,7],
            [gd_dim.y-2.5, 2.5,           3,7],
            [gd_dim.y-2.5, gd_dim.x-2.5,  3,7]];

all_pcb_dim = [
gd_dim,
esp_dim,
// other pcbs can be added to this list...
];

all_pcb_holes = [
gd_holes,
esp_holes,
// other pcbs can be added to this list...
];

include<YAPPgenerator_v17.scad>;
YAPPgenerate();

### CODE REVIEW

**Comment by mrWheel** [comment]
@AustinHaigh 
Not sure. I have no idear how complex using it will be.
Maybe some pictures to make it visual?

**Comment by AustinHaigh** [comment]
Here is a picture of the project I'm working on. It's a box for an ESP32 breakout board (28x52mm) and a garage door remote control PCB (37x58mm). The dimensions of both PCBs are specified in the `all_pcb_dim` variable, and the coordinates of the screw holes (and standoffs) are in the `all_pcb_holes` variable.

https://imgbox.com/nYBsUe73

Does that make it more clear, or would other pictures help?

**Comment by mrWheel** [comment]
Hi AustinHaigh,

Did you send me an eMail about the depth of the screwhead?

I seem to have lost that eMail…

Regards,

Willem

gsm: 0653 - 499 551
www: http://www.aandewiel.nl/ <http://www.aandewiel.nl/> 
---
"I have just one word for you, my boy...plastics." - from "The Graduate"


On 5 Feb 2023, at 22:20, AustinHaigh ***@***.*** ***@***.***> > wrote:


Here is a picture of the project I'm working on. It's a box for an ESP32 breakout board (28x52mm) and a garage door remote control PCB (37x58mm). The dimensions of both PCBs are specified in the all_pcb_dim variable, and the coordinates of the screw holes (and standoffs) are in the all_pcb_holes variable.

https://imgbox.com/nYBsUe73 <https://imgbox.com/nYBsUe73> 

Does that make it more clear, or would other pictures help?

**Comment by AustinHaigh** [comment]
No, I didn't send any messages about screwhead depth.

**Comment by mrWheel** [comment]
I think this can be accomplished with extra standOffs. Adding this makes things way to complicated.

Thanks for your input though!

**Pull request closed without merging**
